kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/is-eks: "true"
spec:
  image: portworx/oci-monitor:<storage_cluster_version_replaceme>
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - type=<portworx_cloud_storage_type_replaceme>,size=<portworx_cloud_storage_size_replaceme>
    journalDeviceSpec: auto
    kvdbDeviceSpec: type=<kvdb_device_storage_type_replaceme>,size=<kvdb_device_storage_size_replaceme>
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  monitoring:
    prometheus:
      enabled: true
      exportMetrics: true
  featureGates:
    CSI: "true"
  env:
  - name: "AWS_ACCESS_KEY_ID"
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: aws-access-key-id
  - name: "AWS_SECRET_ACCESS_KEY"
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: aws-secret-access-key

#    kvdbDeviceSpec: type=gp2,size=150