kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-gitrepo-sc
  annotations:
     storageclass.kubernetes.io/is-default-class: "true"  
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "auto"
allowVolumeExpansion: true

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-db-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "db_remote"
allowVolumeExpansion: true

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-file-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "random"
allowVolumeExpansion: true
